.TH SILLYUTILS "1" "July 2023" "sillyutils 1.0-r6" "Utilities"
.SH NAME
sillyutils \- a collection of my utility tools wrapped into one big script.
.SH SYNOPSIS
lrwxrwxrwx 1 root root 10 Aug 30 16:49 [\fI\,COMMAND\/\fR] -> sillyutils
.SH COMMANDS
.TP
\fB\/hdd_backup\fR
wrap up them dots. or storage.
.TP
\fB\/tbc\fR
originally 'tubecuck', use this to scrape an entire YouTube channel's video IDs.
.TP
\fB\/corntab\fR
like crontab but high in nutritional value, and on the cob!
.TP
\fB\/glog\fR
watch portage do its thing.
.TP
\fB\/loop_despook\fR
kill the Edge instance that FL Studio generates in Wine.
.TP
\fB\/dbus_plasma_wayland_session\fR
did sddm just die? switch to something bette, and call this to launch Plasma.
.SH AUTHOR
Written by draumaz. <https://github.com/draumaz>
