#!/bin/sh

case "${1}" in
  DESTDIR=*) DESTDIR="`echo ${1} | sed 's/DESTDIR=//g'`" ;;
  *) DESTDIR="build" ;;
esac

mkdir -pv ${DESTDIR}/bin

for SCR in *.sh; do
  SCRB="$(echo ${SCR} | sed 's/.sh//g')"
  cp $SCR "${DESTDIR}/bin/${SCRB}"
  chmod -v +x "${DESTDIR}/bin/${SCRB}"
done
