#!/bin/sh

set -x

mkdir -p build/{bin,man/man1}
cd build

cp ../sillyutils.sh bin/sillyutils
cp ../sillyutils.1 man/man1/sillyutils.1

chmod +x bin/sillyutils

# create a symlink for each function.
# sillyutils calls by ${0}.

for LINK in `cat bin/sillyutils | \
  tr ' ' '\n' | \
  grep '()' | \
  tr '()' '\n' | \
  grep '[Aa-zZ]'`; do
    cd ./bin; ln -s sillyutils "${LINK}"; cd ..
    cd ./man/man1; ln -s sillyutils.1 "${LINK}.1"; cd ../..
done
